### ISSUE TITLE
Find a proper way to set dev api-url

### ISSUE THREAD

**Issue by marksverdhei** [LBlend/mann-eller-kvinne#11]
The current soultion requires changing a line of code each time you want to switch it. We should have a .env config or something similar to set react environment variables when switching between dev and build. It might require installing additional dependencies (E.g. webpack or dotenv)

This article describes a couple ways of doing it:
https://trekinbami.medium.com/using-environment-variables-in-react-6b0a99d83cf5

**Comment by LBlend** [comment]
Due to CORS I suggest we also add environment variables to the backend. In order for the backend to accept requests from the frontend, the frontend url needs to be set in the code ([here](https://github.com/LBlend/mann-eller-kvinne/blob/7d093d5abb05034798f25141215ec949d8a42d0c/backend/src/api.py#L8))

I will take a look at some potential solutions to this.
